### PR TITLE
Create Keys Article

### PR DESCRIPTION
**Pull request by Nazeim**

### CODE REVIEW

**Comment by nahern** [comment]
Hi Nazim, has this been reviewed by an SME yet? thanks

**Review by kevinhammond — CHANGES_REQUESTED** [review]
# Keys

 Cardano uses asymmetric cryptography key pairs for:

* Signing and validating payments and staking certificates.
* Managing the blockchain.

 ## Types of keys

 There are three main type of keys in Shelley:
 * Node keys.
 * Address keys.
 * Genesis keys.

 ## Node keys

 Node keys ensure the security of a block producer (stake pool), and include:
 * Operator/operational key,  a cold (offline) key pair with a counter for new certificates.
 * Hot KES key, a hot (online) key pair that can be revoked by the cold key, and that evolves periodically using a Key Evolving Signature (KES) scheme.
 * Block signing key, the operational VRF key pair that is used to create and sign a block when the stake pool is selected as the slot leader.

 ## Address keys

Address keys represent the functions of the addresses derived from the keys for identifying funds on the blockchain that consist of the following keys:

 * Payment key: a key pair that is used to sign/verify transactions, and that determines UTxO addresses.
 * Staking key: a key pair that is used to sign/verify delegation choices and extract rewards, and that determines a rewards address.
 
 ## Genesis keys

Genesis keys are used for blockchain governance purposes.  Normal ada holders and stake pool operators will never need to use these keys.

**Comment by kevinhammond** [comment]
Provided a revised version

**Comment by kevinhammond** [comment]
I am not sure of the following text (we think it relates to Byron rather than Shelley)

The serialized data (address) contains the following two parts:
 * Metadata: that provides off-chain information about the address.
 * Payload: the raw or encoded data.

**Review by nahern — APPROVED** [review]
changes approved

**Pull request merged**
