### PR TITLE
Create Addresses Article

### PR DESCRIPTION
**Pull request by Nazeim**

### CODE REVIEW

**Comment by nahern** [comment]
Hi @Nazeim has this been reviewed by an SME yet?

**Review by kevinhammond — CHANGES_REQUESTED** [review]
# Addresses

 The addresses are a blake2b-256 hash of the relevant verifying/public keys concatenated with some metadata that can be stored on the Cardano blockchain. Shelley introduces four different types of addresses:

 * Base addresses.
 * Pointer addresses.
 * Enterprise addresses.
 * Reward account addresses.

 In addition to those new addresses, Shelley continues to support bootstrap addresses and script addresses as introduced in Byron. However, only the new base and pointer addresses carry stake rights. Addresses are recorded within blocks in a serialised way. The serialized data (address) contains the following two parts:

 * Metadata: that provides off-chain information about the address.
 * Payload: the raw or encoded data.

 ## Base Address

 A base address directly specifies the staking key that controls the stake for the address. The staking rights that are associated with funds held in this address may be exercised by the owner of the staking key. Base addresses can be used in transactions without previously registering the staking key.

Staking rights are exercised by first registering the stake key and then delegating to a stake pool.

 ## Pointer Address

 A pointer address indirectly specifies the stake key that controls the stake for the address. It references a stake key by a stake key pointer (a location on the blockchain of the stake key registration certificate for that key). Pointer addresses can be used in transactions even if their target is not an active stake key registration. This covers the case that the key was unregistered after (or indeed before) the transaction, and also covers pointers to targets that are plainly invalid. The reason for allowing such invalid targets is so that nodes need only track the currently active stake keys.  Pointer address hashes can be considerably shorter than the hash used in base addresses. 

There is a specific subtlety with pointer addresses that needs to be considered:

 it might happen that a stake key registration certificate that is referenced by a pointer address might be lost due to a rollback of the block chain. This should not lead to a loss of funds. To prevent that possibility, the system considers pointer addresses that have an invalid pointer to be valid inputs for transactions (but ignore them for the purpose of Proof-of-Stake participation). Optionally, a wallet might refuse to create transactions to pointer addresses before the referenced certificate has become immutable, in order to prevent funds from being excluded from the Proof-of-Stake protocol in case of blockchain rollbacks.

 ## Enterprise Address

Enterprise addresses carry no staking rights whatsoever. Using them allows completely opting out of participation in the Proof-of-Stake protocol.

One reason for using such addresses is for legal/governance purposes.  For example. exchanges or other organizations that control ada, but hold it on behalf of other users, may wish to, or even be required to, follow a policy of not exercising the associated delegation rights. By using enterprise addresses, it is possible to demonstrate compliance with this policy. Since enterprise addresses are not associated with any stake key, they are automatically excluded from the mechanisms that influence the slot leadership schedule. 

 ## Reward Account Address

 A reward address is a cryptographic hash of the public stake key associated with that address. Reward account addresses are used to distribute rewards for participating in the Proof-of-Stake protocol (either directly or via delegation). They have the following properties:

 * They use account-style accounting, not UTxO-style.
 * They cannot receive funds via transactions. Instead, their balance is only increased when rewards are distributed.
 * There is a one-to-one correspondence between registered stake keys and reward account addresses.

The associated stake key is used whenever funds are withdrawn from a rewards address.

**Comment by kevinhammond** [comment]
I removed this text since I didn't fully understand it

Stake associated with funds in the rewards address contributes to the stake of this key. As with enterprise addresses, the staking object for a reward address does not need to carry any information.

**Review by nahern — APPROVED** [review]
minor edits, changes approved

**Pull request merged**
